### ISSUE TITLE
distorted picture

### ISSUE THREAD

**Issue by varna9000** [tsaarni/esp32-micropython-webcam#2]
Hi, I'm using the camera module (from your .bin build), but not with the example in this repo. I'm trying to email the picture which was taken with camera.capture()

I'm trying to email a jpeg, but for some reason the picture is distorted.
![cam](https://user-images.githubusercontent.com/39020101/58778536-a8553800-85db-11e9-924f-5271b3a0fdee.jpg)

Do you have any idea why the image is like this? The only difference (with respect to the camera code) is that I'm using normal time.sleep() after camera initialisation, instead of uasyncio.sleep() as per your web server code.

What I get as an error in the email client is that there is missing jpeg meta data.

**Comment by tsaarni** [comment]
Unfortunately I don't know what could be wrong.  The image resolution seems correct and browser is not complaining, but the picture itself is of course corrupted.  Are you using exactly the same ESP32 module which I used?  If not, the camera chip could be connected to different ESP32 pins.

**Comment by varna9000** [comment]
Yes, I use 100% your image and esp32-cam (AI Tinker) module - the one shown on the picture in this repo. The camera is connected correctly since the C example from Arduino IDE works ok.  The only reason I can think of is that I'm not sending the correct headers to the smtp protocol. I'll investigate further. I'll try to compile Micropython with your module myself as well and see if it works.

**Comment by varna9000** [comment]
It appears, the problem was with the email headers - I was trying to email the buffer, but forgot to encode base64 the image. All works well now. Thanks :)
