### ISSUE TITLE
Provide ESP32 builds?

### ISSUE THREAD

**Issue by gguuss** [tsaarni/esp32-micropython-webcam#4]
Between dependencies in ESP-IDF and MicroPython, I'm having trouble getting a working build. Would it be possible for you to provide a pre-built release with the .bin file for flashing MicroPython to an ESP32?

**Comment by tsaarni** [comment]
There should be a build on the releases page [here](https://github.com/tsaarni/esp32-micropython-webcam/releases). You'll find bin file inside .tar.gz under "assets".

**Comment by gguuss** [comment]
My hero!

**Comment by tsaarni** [comment]
Just heads up also about issue #3: in this repo I made a mistake by using picoweb as the web framework, unknowingly that it actually targets separate fork of micropython. I have not updated the example code to use standard http server class instead...
