### ISSUE TITLE
frame2bmp

### ISSUE THREAD

**Issue by 470mr0f1** [tsaarni/esp32-micropython-webcam#5]
Hi,
is it possible to use the function "frame2bmp" (included in the camera driver) directly from micropython?
I need to convert the image from .jpg to .bmp or to a pixel array for further processing.
Do you have any other ideas to do that in micropython?

Thanks!

**Comment by tsaarni** [comment]
I think you probably could just try modify https://github.com/tsaarni/micropython-with-esp32-cam/blob/584bc5b2a90becb6b8223bd60f54bdd7405fb651/ports/esp32/modcamera.c#L91 and call `frame2bmp()` from there by adapting the example in the driver's [readme](https://github.com/espressif/esp32-camera/blob/f50b713d6cb6561f0b02820c2acf4393b1c714c3/README.md) file. Alternatively you could add a new function which would return the image as BMP, or add a parameters for setting image format...

You likely know this already, but a warning here that this is bit involved process: modifying C-based  micropython modules requires (re)compiling micropython itself.  

In my example [here](https://github.com/tsaarni/micropython-with-esp32-cam/wiki) I used a fork of the camera driver with very small modification which you can see [here](https://github.com/tsaarni/esp32-camera-for-micropython/commit/e450d21841a164bd92bdce72e54ea35557800c30).  My fork is old so you would need to uplift a version of the driver which now includes `frame2bmp()` function.

Hope this helps!

**Comment by tsaarni** [comment]
Regarding any other ideas: I do not know if there is pure-python image library that would be capable of converting image format and which would be compatible with micropython.  If you did not do it already, I guess it is worth of googling a bit!

**Comment by 470mr0f1** [comment]
Thanks alot for your input!
I already googled a lot regarding a pure-python image library which is compatible with micropython.
I think the best thing is to modify the driver and recompile micropython.

Thanks again for your comments!
